### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by sandstranger** [OpenMW/openmw-template#2]
I have got this error , with loading island.omwaddon , without this addon , there is no land
http://imgur.com/a/IvYVR

**Comment by psi29a** [comment]
It would seem that a few records are missing, someone else mentioned it a few weeks ago.  I think I have an idea, the island.omwaddon was made from an old version of openmw-cs, so I'll do another conversion next week and upload a new version of the openmw-template that works with >= 0.37. :)

**Comment by psi29a** [comment]
Fixed upstream. 0.38
